cluster:
  ssoAuthUrl: https://dev.loginproxy.gov.bc.ca/auth
  cmsUrl: https://dev-cms.bcparks.ca

frontend:
  env:
    externalUrl: https://dev-staff.bcparks.ca
    publicUrl: https://dev.bcparks.ca

backend:
  env:
    externalUrl: https://dev-staff-api.bcparks.ca

