cluster:
  ssoAuthUrl: https://loginproxy.gov.bc.ca/auth
  cmsUrl: https://alpha-test-cms.bcparks.ca

images:
  frontend:
    tag: training
  backend:
    tag: training

frontend:
  env:
    externalUrl: https://training-staff.bcparks.ca
    publicUrl: https://alpha-test.bcparks.ca

backend:
  env:
    externalUrl: https://training-staff-api.bcparks.ca
    devTestMode: "true"
  postgresSecret: crunchy-postgres-training-pguser-postgres

cron:
  enabled: true
